name: Integración continua
on: push origin HEAD
jobs:
  compilar-y-ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: clonar el repositorio
        uses: actions/checkout@v4
      - name: compilar codigo
        run: gcc main.c -o main